package metrics

import (
	"net/http"
	"strconv"
	"time"

	"MediaDetox/internal/domain"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

type PrometheusMetrics struct {
	httpRequestsTotal     *prometheus.CounterVec
	httpRequestDuration   *prometheus.HistogramVec
	eventsRegisteredTotal *prometheus.CounterVec
	alertsGeneratedTotal  *prometheus.CounterVec
	repositoryOpsTotal    *prometheus.CounterVec
	repositoryOpsDuration *prometheus.HistogramVec
}

func NewPrometheusMetrics() *PrometheusMetrics {
	return &PrometheusMetrics{
		httpRequestsTotal: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "mediadetox_http_requests_total",
			Help: "Total number of HTTP requests handled by the API.",
		}, []string{"method", "path", "status"}),
		httpRequestDuration: promauto.NewHistogramVec(prometheus.HistogramOpts{
			Name:    "mediadetox_http_request_duration_seconds",
			Help:    "HTTP request duration in seconds.",
			Buckets: prometheus.DefBuckets,
		}, []string{"method", "path", "status"}),
		eventsRegisteredTotal: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "mediadetox_events_registered_total",
			Help: "Total number of usage events registered by the API.",
		}, []string{"app_name", "event_type", "user_id"}),
		alertsGeneratedTotal: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "mediadetox_alerts_generated_total",
			Help: "Total number of alerts generated by the rule engine.",
		}, []string{"type", "severity", "user_id"}),
		repositoryOpsTotal: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "mediadetox_repository_operations_total",
			Help: "Total number of repository operations.",
		}, []string{"repository", "operation", "status"}),
		repositoryOpsDuration: promauto.NewHistogramVec(prometheus.HistogramOpts{
			Name:    "mediadetox_repository_operation_duration_seconds",
			Help:    "Repository operation duration in seconds.",
			Buckets: prometheus.DefBuckets,
		}, []string{"repository", "operation", "status"}),
	}
}

func (m *PrometheusMetrics) Handler() http.Handler {
	return promhttp.Handler()
}

func (m *PrometheusMetrics) Middleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		recorder := &statusRecorder{
			ResponseWriter: w,
			status:         http.StatusOK,
		}
		start := time.Now()

		next.ServeHTTP(recorder, r)

		status := strconv.Itoa(recorder.status)
		path := routeLabel(r.URL.Path)
		m.httpRequestsTotal.WithLabelValues(r.Method, path, status).Inc()
		m.httpRequestDuration.WithLabelValues(r.Method, path, status).Observe(time.Since(start).Seconds())
	})
}

func (m *PrometheusMetrics) RecordEventRegistered(event domain.Event) {
	m.eventsRegisteredTotal.WithLabelValues(event.AppName, string(event.EventType), event.UserID).Inc()
}

func (m *PrometheusMetrics) RecordAlertGenerated(alert domain.Alert) {
	m.alertsGeneratedTotal.WithLabelValues(alert.Type, alert.Severity, alert.UserID).Inc()
}

func (m *PrometheusMetrics) RecordRepositoryOperation(repository, operation string, duration time.Duration, err error) {
	status := "ok"
	if err != nil {
		status = "error"
	}

	m.repositoryOpsTotal.WithLabelValues(repository, operation, status).Inc()
	m.repositoryOpsDuration.WithLabelValues(repository, operation, status).Observe(duration.Seconds())
}

type statusRecorder struct {
	http.ResponseWriter
	status int
}

func (r *statusRecorder) WriteHeader(status int) {
	r.status = status
	r.ResponseWriter.WriteHeader(status)
}

func routeLabel(path string) string {
	if path == "/metrics" {
		return "/metrics"
	}
	if path == "/events" {
		return "/events"
	}
	if path == "/rules" {
		return "/rules"
	}
	if len(path) >= len("/users/") && path[:len("/users/")] == "/users/" {
		return "/users/{id}/..."
	}
	return "unknown"
}
